version: '3.7'

services:
  dev:
    container_name: dev
    image: busybox
    command: tail -f /dev/null
    depends_on:
      - grafana
      - loki
      - prometheus
      - promtail
      - tempo

  app:
    container_name: ${NAME}
    image: ${IMAGE}:latest
    user: 0:0
    network_mode: 'host'
    ports:
      - 3100:3100
      - 5000:5000
    volumes:
      - ./data/logs:/var/logs
    environment:
      DEBUG: '1'
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
      KEYCLOAK_BASE_URL: http://localhost:8080
      KEYCLOAK_CLIENT_ID: app
      KEYCLOAK_CLIENT_SECRET: P@ssw0rd
      LOG_FILE_NAME: /var/logs/app.log
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://tempo:14268/api/traces
      OTEL_SERVICE_NAME: app
      SWAGGER: '1'

  tempo:
    image: grafana/tempo:1.5.0
    user: 0:0
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo:/tmp/tempo
    ports:
      - 14268:14268
      - 14250:14250
      - 55680:55680
      - 6831/udp
      - 6832/udp

  loki:
    user: 0:0
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/loki-local.yaml
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=const
    volumes:
      - ./loki.yaml:/etc/loki/loki-local.yaml
      - loki:/tmp/loki

  promtail:
    user: 0:0
    image: grafana/promtail:2.2.1
    command: -config.file=/etc/promtail/promtail-local.yaml
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail-local.yaml
      - ./data/logs:/app/logs
    depends_on:
      - loki

  prometheus:
    user: 0:0
    image: prom/prometheus:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - 9090:9090

  grafana:
    user: 0:0
    image: grafana/grafana:9.1.1-ubuntu
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3080:3000
    depends_on:
      - prometheus
      - tempo
      - loki

volumes:
  tempo:
    name: tempo-${NAME}
  loki:
    name: loki-${NAME}
